version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: make-it-rain-db
    environment:
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-password}
      POSTGRES_DB: ${DATABASE_NAME:-make_it_rain}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: make-it-rain-app
    ports:
      - "8080:8080"
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: ${DATABASE_USER:-postgres}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-password}
      DATABASE_NAME: ${DATABASE_NAME:-make_it_rain}
      DATABASE_SSL_MODE: disable
      SERVER_PORT: 8080
      SERVER_ENVIRONMENT: ${SERVER_ENVIRONMENT:-development}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY:-secret-key-change-in-production}
      APP_LOG_LEVEL: ${APP_LOG_LEVEL:-info}
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data: